### PR TITLE
Fallback to date format if datetime format doesn't work

### PR DESCRIPTION
**Pull request by IanButterworth**
A proposed fix for #80

Another approach would be to make the preprocessing format string exposed & customizable

### CODE REVIEW

**Review by reiniervlinschoten — APPROVED** [review]

**Comment by reiniervlinschoten** [comment]
Added it to next version, thank you very much!

**Comment by IanButterworth** [comment]
Great. I should add that it is untested by me. Are there package tests that can be run?

**Comment by IanButterworth** [comment]
I now see that the tests failed on the merged commit. It seems it would be helpful to run CI on PRs too?

**Comment by IanButterworth** [comment]
Suggested fix in #82

**Comment by reiniervlinschoten** [comment]
Yeah, I did not run in on your PR as I redirected it to an incoming version update so I left the CI to the new PR and fixed the issue in the new version.

**Pull request merged**
